print("this is string")
print('this is string')
print("""this is string""")
print(type('''this is string'''))
print(type(5))
print(type(5.0))
print(type(5.968796))
print(type(True))
print(type(False))
print(type("hfuhfdugh"))
print(type("s"))
print(type('s'))
